name: GitHub Actions Data Sharing
# run-name: ${{ github.actor }} is testing out GitHub Actions ðŸš€
on:
  push:
    ## on pushes to given branches
    branches: main
  workflow_dispatch:
  pull_request:
    types: closed
defaults:
  run:
    shell: pwsh
jobs:
  make-some-dater:
    runs-on: ubuntu-latest
    outputs:
      myCoolDataFromSingleLine: ${{ steps.set_step_output.outputs.my_step_output-singleLine }}
      myCoolDataFromMultiline: ${{ steps.set_step_output.outputs.my_step_output-multiLine }}
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: set outputs JSON value
        id: set_step_output
        run: |-
          echo "ðŸŽ‰ The job was automatically triggered by event '${{ github.event_name }}'"
          echo "ðŸ§ This job is now running on a '${{ runner.os }}' server hosted by GitHub!"
          echo "ðŸ”Ž Branch '${{ github.ref }}', in repository '${{ github.repository }}'"
          Write-Verbose -Verbose -Message "Value of `$env:GITHUB_OUTPUT: '$env:GITHUB_OUTPUT'"
          Write-Verbose -Verbose -Message "Setting some output items for use by later jobs"
          ## some `runner` context info at https://docs.github.com/en/actions/learn-github-actions/contexts#runner-context
          $arrFilesystemItems = Get-ChildItem '${{ runner.tool_cache }}' | Select-Object -Property Mode, LastWriteTime, Length, Name
          Write-Verbose -Verbose -Message "Using redirection/append operator '>>'"
          Write-Output "my_step_output-singleLine=$($arrFilesystemItems | ConvertTo-Json -Depth 10 -Compress)" >> $env:GITHUB_OUTPUT
          ## can use multi-line strings as values, too; docs at https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#setting-an-output-parameter, which link to "Multiline strings" in same doc, too
          ## notice no assignment character (no '=') when using multiline in GHA
          $strSomeGuid = (New-Guid).Guid
          Write-Verbose -Verbose -Message "Using standard PowerShell cmdlet for adding content"
          Add-Content -Path $env:GITHUB_OUTPUT -Value "my_step_output-multiLine<<$strSomeGuid`n$($arrFilesystemItems | ConvertTo-Json -Depth 10)`n$strSomeGuid" -Encoding utf8
          Write-Verbose -Verbose -Message "Getting contents of '`$env:GITHUB_OUTPUT':"
          Get-Content -Path $env:GITHUB_OUTPUT
      - run: |-
          echo "ðŸ’¡ The ${{ github.repository }} repository has been cloned to the runner."
          echo "ðŸ–¥ï¸ The workflow is now ready to test your code on the runner."
      - run: echo "ðŸ This job's status is ${{ job.status }}."

  use-some-dater:
    runs-on: ubuntu-latest
    needs: make-some-dater
    steps:
      - name: use data from previous job
        run: |-
          Write-Verbose -Verbose -Message ("Single-quoted value of 'needs.make-some-dater.outputs.myCoolDataFromSingleLine': '{0}'" -f '${{needs.make-some-dater.outputs.myCoolDataFromSingleLine}}')
          Write-Verbose -Verbose -Message ("Single-quoted value of 'needs.make-some-dater.outputs.myCoolDataFromMultiline': '{0}'" -f '${{needs.make-some-dater.outputs.myCoolDataFromMultiline}}')
          $oMyCoolObject = @{Name = " San Roscoe"; Datetime = Get-Date; DirectoryListing = '${{needs.make-some-dater.outputs.myCoolDataFromSingleLine}}' | ConvertFrom-Json}
          Write-Verbose -Verbose -Message "JSON of new object created with outputs value as sub property: `n'$($oMyCoolObject | ConvertTo-Json -Depth 10)'"
